### ISSUE TITLE
Error installing pip

### ISSUE THREAD

**Issue by RCAlfonso** [pypa/pypa.io#30]
Am trying to install the latest pip but am getting this error. 

[root@tgsex08 ~]# python get-pip.py
Traceback (most recent call last):
  File "get-pip.py", line 20649, in <module>
    main()
  File "get-pip.py", line 197, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    import pip._internal
  File "/tmp/tmpAKbzin/pip.zip/pip/_internal/__init__.py", line 42, in <module>

  File "/tmp/tmpAKbzin/pip.zip/pip/_internal/cmdoptions.py", line 16, in <module>
  File "/tmp/tmpAKbzin/pip.zip/pip/_internal/index.py", line 526
    {str(c.version) for c in all_candidates},
                      ^
SyntaxError: invalid syntax

**Comment by mdivk** [comment]
I am having this issue too.

**Comment by xavfernandez** [comment]
Hello, `get-pip` errors should be reported to https://github.com/pypa/get-pip.

You are likely using python 2.6 and hitting: https://github.com/pypa/get-pip/issues/29.
