### ISSUE TITLE
python2 get-pip.py invalid syntax

### ISSUE THREAD

**Issue by sheikki** [pypa/pypa.io#67]
```
python2 get-pip.py
Traceback (most recent call last):
  File "get-pip.py", line 24244, in <module>
    main()
  File "get-pip.py", line 199, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    from pip._internal.cli.main import main as pip_entry_point
  File "/tmp/tmp9nhFm7/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
```

**Comment by sheikki** [comment]
Nevermind, found a solution from https://github.com/pypa/pip/issues/9500
